apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-processor-backend
  labels:
    app: payment-processor-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-processor-backend
  template:
    metadata:
      labels:
        app: payment-processor-backend
    spec:
      containers:
      - name: wasapp
        image: 192.168.0.136/payment-processor-backend
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
        - containerPort: 9443
